[tools]
python = "latest"
ruby = "latest"
node = "latest"
lua = "latest"
zig = "latest"
go = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
# disable_backends = ["asdf"]
